version: "3.8"
services:
  databases:
      image: postgres:16.1-alpine3.18
      restart: on-failure
      container_name: pg-next
      environment:
         - "POSTGRES_USER=admin"
         - "POSTGRES_PASSWORD=password"
         - "POSTGRES_DB=next_db"
      volumes:
        - ./pgdata:/var/lib/postgresql/data
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
      - "4500:5432"
